name: hive_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 0.8.2
homepage: https://github.com/hivedb/hive/tree/master/hive_generator
documentation: https://docs.hivedb.dev/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.2.1
  source_gen: ^1.2.1
  hive: ^2.0.5
  analyzer: ^3.0.0
  dartx: ^1.0.0
  built_value: ^8.1.3
  built_collection: ^5.1.1

dev_dependencies:
  test: ^1.20.1
  build_test: ^2.1.5
  build_runner: ^2.1.7
  pedantic: ^1.11.1
